# Generated by Django 3.0.3 on 2020-02-18 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StarshipClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swapi_url', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('cost_in_credits', models.IntegerField(null=True)),
                ('crew', models.IntegerField(null=True)),
                ('passengers', models.IntegerField()),
                ('cargo_capacity', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('starship_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encounters.StarshipClass')),
            ],
        ),
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobs', to='encounters.Encounter')),
                ('starship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encounters.Starship')),
            ],
        ),
    ]
